### ISSUE TITLE
Question: Unity Package source

### ISSUE THREAD

**Issue by Alexandre-Belhomme** [uzair-ashraf/vrc-owo-suit#1]
Hello, first thank you a lot for this project (i don't have it installed yet and still waiting for my suit to arrive).

I wondered as the unity package is in the project, if we have the source code of this unity package ?

Thank you.

**Comment by Alexandre-Belhomme** [comment]
> Hello, how to directly install it now what is the L and R Dorsal?

That's not really relevant to the topic but sure.

The main Untity file to install is a file ending in ".unitypackage".

You can double click on it or drag it in your unity window to install it.

The L and R dorsals are places where the actual OWO Suit plates would be places if you would have to place them on your avatar.

The point is to place the vrchat colliders at the spot where they would match their IRL position.

If you have more questions, maybe create a dedicated issue.

**Comment by TheDeadRedSkull** [comment]
no i mean what are the dorsals on the body bc my main isnt english
